# Generated by Django 5.1.2 on 2024-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdone',
            name='description',
            field=models.TextField(default='Brak opisu'),
        ),
        migrations.AddField(
            model_name='projectsdone',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsdone',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsdone',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
